spring:
  application:
    name: invoice-taulia

#  security:
#    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/invoicedb
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
